version: "3.9"

services:
  game:
    image: apellun/game:latest
    command: gunicorn app:app -b 0.0.0.0:3000
    ports:
      - 3000:3000
    restart: always
    environment:
      - FLASK_ENV="development"
      - FLASK_APP=app:app


  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always